(() => {
  const THEORY = [
    ["PY-T001","What is Python and why is it commonly used in data analysis?","Easy","Python is a general-purpose programming language with a large data ecosystem. For data analysis, libraries such as Pandas, NumPy, Matplotlib and scikit-learn provide ready-to-use tools for data cleaning, analysis, visualization and modeling.","Interview answer: Python is popular in analytics because it is readable, has strong data libraries, and lets analysts move from data cleaning to visualization and machine learning in one environment.","Example: import pandas as pd; df = pd.read_csv('sales.csv'); print(df.groupby('region')['sales'].sum())","Do not say Python is only a data-analysis language. It is a general-purpose language used across many domains.","Python = readable language + large analytics ecosystem."],
    ["PY-T002","What is the difference between a list, tuple, set and dictionary?","Easy","A list is ordered and mutable. A tuple is ordered and immutable. A set stores unique values and is useful for membership checks. A dictionary stores key-value pairs and is useful when values are looked up by a key.","Interview answer: I choose the structure based on the requirement. Lists are good for ordered collections, tuples for fixed collections, sets for uniqueness, and dictionaries for key-value mapping.","Example: nums=[1,2,2]; point=(10,20); unique={1,2}; employee={'name':'Akshay','salary':70000}","A set is not the right choice when you need duplicate values or positional indexing.","List = ordered/mutable, Tuple = ordered/immutable, Set = unique values, Dict = key-value pairs."],
    ["PY-T003","What is the difference between mutable and immutable objects?","Easy","Mutable objects can be changed after creation. Immutable objects cannot be changed in place. Lists and dictionaries are common mutable objects, while strings, integers and tuples are immutable.","Interview answer: Mutability matters because changing a mutable object can affect other references to the same object, while an immutable object must be replaced with a new value.","Example: a=[1,2]; a.append(3) changes the list. A string such as s='abc' cannot be changed in place.","Do not confuse reassignment with mutation. x='a'; x='b' creates a new reference/value rather than modifying the original string.","Mutable = can change in place. Immutable = cannot change in place."],
    ["PY-T004","What is a variable in Python?","Easy","A variable is a name that refers to an object. Python uses dynamic typing, so the type is associated with the object rather than being declared in the variable name.","Interview answer: I can assign different object types to the same variable name, although in production code I keep variable meaning and types clear.","Example: x=10; x='Akshay' is valid Python because the name x can refer to different objects at different times.","Avoid saying Python has no types. Python is dynamically typed, but objects still have types.","A variable is a reference to an object."],
    ["PY-T005","What is the difference between == and is?","Easy","== compares values. is checks object identity, meaning whether two references point to the same object. For normal value comparison, use ==.","Interview answer: I use == when I care about equality of values and is mainly for identity checks, commonly with None.","Example: a=[1,2]; b=[1,2]; a == b is True, but a is b is False because they are different list objects.","Do not use is as a replacement for == when comparing ordinary values.","== = value equality, is = object identity."],
    ["PY-T006","What are functions in Python?","Easy","A function is a reusable block of code defined with def. It can receive parameters and return a result. Functions reduce duplication and make analytics code easier to test and maintain.","Interview answer: I use functions to separate reusable business logic, such as cleaning a column, calculating a KPI, or validating input.","Example: def revenue(price, qty): return price * qty","Avoid writing one very large function. Keep functions focused on one logical task.","Function = reusable logic with inputs and optional output."],
    ["PY-T007","What is a lambda function?","Easy","A lambda is a small anonymous function containing an expression. It is useful for short transformations, sorting keys and simple callbacks.","Interview answer: I use lambda for short logic where defining a full function would add unnecessary code. For complex logic, I prefer def.","Example: employees.sort(key=lambda x: x['salary'], reverse=True)","Do not use lambda for long or complicated business logic because readability suffers.","Lambda = short anonymous function."],
    ["PY-T008","What is list comprehension?","Easy","List comprehension is a concise way to create a list from an iterable, optionally applying a transformation and a condition.","Interview answer: It is useful for simple transformations, but I avoid making comprehensions too complex.","Example: squares=[x*x for x in range(1,6)]","A deeply nested comprehension can be harder to read than a normal loop.","Comprehension = compact loop for creating a collection."],
    ["PY-T009","What is exception handling in Python?","Easy","try and except allow a program to handle expected runtime errors. else can run when no exception occurs and finally can be used for cleanup.","Interview answer: I catch specific exceptions where possible and avoid hiding unexpected errors with a broad except.","Example: try: value=int(text) except ValueError: value=0","Do not silently catch every error with except Exception unless there is a clear reason and logging.","Exception handling makes failure controlled and understandable."],
    ["PY-T010","What is the difference between append() and extend()?","Easy","append adds one object as one element. extend iterates over another iterable and adds its elements individually.","Interview answer: If I append [3,4] to [1,2], the result is [1,2,[3,4]]. If I extend it, the result is [1,2,3,4].","Example: a=[1,2]; a.append([3,4]); b=[1,2]; b.extend([3,4])","Remember that strings are iterables, so extend('abc') adds a, b and c separately.","append = one element, extend = elements from iterable."],
    ["PY-T011","What is NumPy?","Easy","NumPy is a numerical computing library built around efficient multidimensional arrays and vectorized operations. It is widely used underneath the Python data ecosystem.","Interview answer: NumPy is useful for numerical operations and arrays, while Pandas provides higher-level labeled tabular structures.","Example: import numpy as np; arr=np.array([10,20,30]); print(arr.mean())","Do not say NumPy is a database. It is a numerical computing library.","NumPy = fast numerical arrays and operations."],
    ["PY-T012","What is Pandas?","Easy","Pandas is a Python library for working with structured and time-series data. Its core objects are Series and DataFrame.","Interview answer: I use Pandas for loading data, cleaning missing values, filtering, grouping, joining, reshaping and preparing datasets for analysis.","Example: df=pd.DataFrame({'department':['IT','HR'],'salary':[70000,60000]})","Do not treat a DataFrame as a database. It is an in-memory data structure.","Pandas = tabular data analysis in Python."],
    ["PY-T013","What is a Pandas Series?","Easy","A Series is a one-dimensional labeled array. It has values and an index and can represent a single analytical variable or column.","Interview answer: A DataFrame column is typically represented as a Series.","Example: s=pd.Series([10,20,30], name='sales')","A Series is one-dimensional, while a DataFrame is two-dimensional.","Series = one labeled column-like structure."],
    ["PY-T014","What is a Pandas DataFrame?","Easy","A DataFrame is a two-dimensional labeled table with rows and columns. It is similar to a spreadsheet or a relational query result, but it lives in Python memory.","Interview answer: I use DataFrame for most data-cleaning and analysis workflows because each column can represent a variable.","Example: df=pd.DataFrame({'name':['A','B'],'salary':[50000,70000]})","Keep track of the row grain and column data types when working with a DataFrame.","DataFrame = rows + columns + labels."],
    ["PY-T015","How do you inspect the first and last rows of a DataFrame?","Easy","Use head() for the first rows and tail() for the last rows. Passing a number controls how many rows are displayed.","Interview answer: After loading data, I normally inspect head, shape, columns and info before analysis.","Example: df.head(10); df.tail(5)","Do not assume the first rows represent the entire dataset. They are only an initial inspection.","head() = first rows, tail() = last rows."],
    ["PY-T016","What is the difference between loc and iloc?","Easy","loc selects by labels and boolean conditions. iloc selects by integer position.","Interview answer: I use loc when the condition or index label is meaningful and iloc when I need positional selection.","Example: df.loc[df['salary']>50000, ['name','salary']]; df.iloc[0:5,0:2]","With loc, the end of a label-based slice can be inclusive. With iloc, slicing follows normal Python positional rules.","loc = labels/conditions, iloc = positions."],
    ["PY-T017","How do you check DataFrame shape and column names?","Easy","df.shape returns a tuple containing row count and column count. df.columns returns the column labels.","Interview answer: I use these checks early to confirm the dataset structure before transforming it.","Example: rows, cols = df.shape; print(df.columns.tolist())","Do not call shape like a function. It is a property.","shape = dimensions, columns = column labels."],
    ["PY-T018","How do you check data types in Pandas?","Easy","Use df.dtypes to inspect each column type and df.info() for a compact schema, non-null counts and memory information.","Interview answer: I check types before analysis because dates, numeric values and text require different operations.","Example: df.dtypes; df.info()","A numeric-looking column can still be stored as text, so dtype validation matters.","dtypes/info = schema inspection."],
    ["PY-T019","What is groupby in Pandas?","Easy","groupby splits data into groups based on one or more keys, applies an aggregation or transformation, and returns grouped results.","Interview answer: I use groupby for business KPIs such as revenue by region, average salary by department or orders by customer.","Example: df.groupby('department')['salary'].mean()","Always confirm the intended grain before grouping so the KPI is not accidentally calculated at the wrong level.","groupby = split, calculate, combine."],
    ["PY-T020","What is the difference between merge and concat?","Medium","merge combines DataFrames using matching keys, similar to SQL JOIN. concat combines objects along rows or columns without requiring a key match.","Interview answer: If I have customer and order tables and need to match customer_id, I use merge. If I need to stack monthly files with the same schema, I use concat.","Example: pd.merge(orders, customers, on='customer_id', how='left'); pd.concat([jan,feb])","Using concat when you actually need key matching can produce incorrect row structures.","merge = key-based combination, concat = axis-based combination."],
    ["PY-T021","How do you handle missing values in Pandas?","Easy","First measure missingness with isna() or isnull(). Then choose a strategy based on business meaning: drop, fill with a constant, use an aggregate, or carry values forward/backward for suitable time-series cases.","Interview answer: I do not automatically replace every missing value with zero. I first understand what NULL means for that field.","Example: df['salary']=df['salary'].fillna(df['salary'].median())","Replacing missing values without understanding the business meaning can introduce bias.","Missing-value treatment should be business-driven."],
    ["PY-T022","What is the difference between dropna() and fillna()?","Easy","dropna removes rows or columns with missing values. fillna replaces missing values with a chosen value or strategy.","Interview answer: I use dropna when missing records cannot be used and fillna when a defensible replacement exists.","Example: df.dropna(subset=['customer_id']); df['city']=df['city'].fillna('Unknown')","Do not drop rows simply because a column has some missing values. Check how much data would be lost.","dropna = remove, fillna = replace."],
    ["PY-T023","How do you remove duplicate rows?","Easy","Use drop_duplicates(). The subset parameter can define which columns determine whether records are duplicates.","Interview answer: I identify the business key first and then remove or flag duplicates based on that key.","Example: df.drop_duplicates(subset=['customer_id','order_id'])","A duplicate row is not always an error. Repeated transactions can be valid business events.","Duplicates should be evaluated using business grain."],
    ["PY-T024","How do you filter rows in Pandas?","Easy","Use boolean conditions inside df[]. Multiple conditions use & for AND and | for OR, with parentheses around each condition.","Interview answer: I use explicit boolean masks so the filtering logic is easy to review and test.","Example: df[(df['salary']>50000) & (df['department']=='IT')]","Use & and | instead of Python and/or for Series conditions.","Filtering = boolean mask."],
    ["PY-T025","What does apply() do in Pandas?","Medium","apply() applies a function to a Series or along a DataFrame axis. It is useful for custom logic, but vectorized operations are usually preferred when available.","Interview answer: I use apply when the logic is genuinely custom and cannot be expressed clearly with a vectorized operation.","Example: df['grade']=df['salary'].apply(lambda x: 'High' if x>=80000 else 'Normal')","Row-wise apply on a large DataFrame can be slow compared with vectorized operations.","apply = flexible custom function, not automatically the fastest choice."],
    ["PY-T026","What is vectorization in Pandas?","Medium","Vectorization means operating on whole arrays or columns rather than processing each row in a Python loop. It usually improves speed and readability.","Interview answer: For large datasets, I prefer vectorized expressions such as df['revenue']=df['price']*df['quantity'] instead of iterrows().","Example: df['revenue']=df['price']*df['quantity']","Do not assume every vectorized expression is automatically optimal. Measure performance for critical workflows.","Vectorization = operate on columns/arrays efficiently."],
    ["PY-T027","How do you sort a DataFrame?","Easy","Use sort_values() and specify ascending or descending order. Multiple columns can be passed as a list.","Interview answer: I use sorting for ranking, top-N analysis and ordered reporting.","Example: df.sort_values('salary', ascending=False)","Sorting changes row order, not the underlying business meaning of the data.","sort_values = order rows by values."],
    ["PY-T028","How do you rename columns?","Easy","Use rename(columns={...}) for selected columns or assign a complete list to df.columns when renaming all columns.","Interview answer: I standardize column names early so downstream code uses consistent names.","Example: df.rename(columns={'Salary':'salary'})","Keep names consistent and avoid unnecessary spaces or mixed naming styles.","rename = standardize labels."],
    ["PY-T029","How do you convert a column to datetime?","Easy","Use pd.to_datetime(). errors='coerce' can convert invalid values to NaT so they can be inspected and handled.","Interview answer: I convert date columns before date filtering, grouping or time-series calculations.","Example: df['order_date']=pd.to_datetime(df['order_date'], errors='coerce')","Invalid dates converted to NaT should be reviewed rather than silently ignored.","Datetime conversion is essential for reliable date analysis."],
    ["PY-T030","What is a pivot table in Pandas?","Medium","pivot_table summarizes data across dimensions using an aggregation such as sum, mean or count. It is useful for business reporting.","Interview answer: I use pivot tables when I need a compact cross-tab summary, such as sales by region and product category.","Example: pd.pivot_table(df, values='sales', index='region', columns='category', aggfunc='sum')","Always verify whether the default aggregation matches the business question.","pivot_table = multidimensional summary."],
    ["PY-T031","What is the difference between map(), apply(), and DataFrame.map()?","Medium","Series.map is commonly used for mapping or element-wise transformation of a Series. apply is more flexible and can operate across a Series or DataFrame axis. DataFrame.map applies an element-wise function to DataFrame values.","Interview answer: I choose the simplest operation that matches the transformation and prefer vectorized operations when possible.","Example: df['status']=df['status'].map({'A':'Active','I':'Inactive'})","Do not use apply for a simple dictionary mapping when map is clearer.","map = mapping/element-wise Series transform, apply = flexible function."],
    ["PY-T032","How do you select one or multiple columns?","Easy","Use df['column'] for one column and df[['column1','column2']] for multiple columns.","Interview answer: I select only the columns needed for a transformation or analysis to keep code and memory use clear.","Example: df[['employee_name','salary']]","Remember the double brackets when selecting multiple columns as a DataFrame.","One column uses one label; multiple columns use a list."],
    ["PY-T033","What is an index in Pandas?","Easy","The index labels rows. It can be a default integer index or meaningful labels such as dates or IDs.","Interview answer: I use the index when it naturally represents row labels, especially in time-series analysis, but I do not treat it as a business key automatically.","Example: df.set_index('order_date')","An index is not automatically unique unless the data and operation guarantee uniqueness.","Index = row labels."],
    ["PY-T034","Why should you avoid chained assignment in Pandas?","Medium","Chained assignment can make it unclear whether you are modifying the original DataFrame or a temporary object. Use loc for explicit assignment.","Interview answer: I prefer df.loc[condition,'column']=value because the target of the assignment is explicit.","Example: df.loc[df['salary']<0,'salary']=None","Do not rely on ambiguous chained expressions such as df[df['salary']<0]['salary']=None.","loc makes assignment explicit."],
    ["PY-T035","How do you calculate percentage change?","Easy","Series.pct_change() calculates relative change from the previous observation.","Interview answer: I use pct_change for month-over-month or period-over-period growth and multiply by 100 when presenting it as a percentage.","Example: df['growth_pct']=df['sales'].pct_change()*100","The first observation has no previous period and is normally NaN.","pct_change = relative period-over-period change."],
    ["PY-T036","How do you calculate cumulative totals?","Easy","cumsum() calculates a running cumulative sum. It is useful for cumulative revenue, units or balances.","Interview answer: I sort by the correct date or sequence first, then calculate the cumulative value.","Example: df=df.sort_values('date'); df['running_sales']=df['sales'].cumsum()","If the data is not ordered correctly, a running total can be misleading.","cumsum = running total."],
    ["PY-T037","How do you find the top N rows?","Easy","You can sort descending and use head(N), or use nlargest for a numeric column.","Interview answer: For a simple top-N report, sort_values plus head is clear. nlargest can be convenient for numeric columns.","Example: df.nlargest(5,'sales')","Check whether ties should all be included. Top five rows and top five distinct values are different requirements.","Top-N depends on whether ties matter."],
    ["PY-T038","How do you find unique values and their counts?","Easy","unique() returns distinct values. value_counts() returns the frequency of each value.","Interview answer: I use value_counts during data profiling to understand categories, invalid labels and distribution.","Example: df['department'].value_counts(dropna=False)","Do not confuse number of unique values with number of rows.","unique = distinct values, value_counts = frequencies."],
    ["PY-T039","What is an inner merge versus a left merge?","Medium","An inner merge keeps rows whose keys match in both DataFrames. A left merge keeps every row from the left DataFrame and adds matching right-side values; unmatched right columns become missing.","Interview answer: I use left merge when the left table is the population I must preserve, such as all customers, even if some have no orders.","Example: customers.merge(orders,on='customer_id',how='left')","A one-to-many merge can increase row count. Always check the join grain.","Inner = matches only. Left = keep all left rows."],
    ["PY-T040","How would you optimize a slow Pandas workflow?","Hard","First identify the bottleneck. Then prefer vectorized operations, select only required columns, use appropriate dtypes, avoid unnecessary copies, reduce row-wise apply and process large files in chunks when appropriate.","Interview answer: I optimize based on profiling rather than guessing. I also check whether the problem should be solved in SQL or a database before loading everything into memory.","Example: pd.read_csv('large.csv', usecols=['id','sales'], chunksize=100000)","Do not optimize blindly. A faster operation that changes the business result is not an improvement.","Profile first, then optimize the actual bottleneck."],
    ["PY-T041","How do you detect outliers using IQR?","Medium","Calculate Q1 and Q3, compute IQR = Q3-Q1, then flag values below Q1-1.5*IQR or above Q3+1.5*IQR.","Interview answer: IQR is a robust rule for identifying potential outliers, but I confirm whether an extreme value is an error or a genuine business event before removing it.","Example: q1=df['salary'].quantile(.25); q3=df['salary'].quantile(.75); iqr=q3-q1","An outlier is not automatically bad data.","IQR helps flag unusual values; business validation decides what to do."],
    ["PY-T042","How do you create a new column from existing columns?","Easy","Assign an expression to a new column. Pandas will operate element-wise for compatible Series expressions.","Interview answer: I create derived columns for business metrics such as revenue, margin, age or conversion rate.","Example: df['revenue']=df['price']*df['quantity']","Check for missing values and incompatible types before arithmetic.","Derived column = explicit business transformation."],
    ["PY-T043","How do you group by multiple columns?","Easy","Pass a list of grouping columns to groupby. The result is calculated at the combined grain of those columns.","Interview answer: I use multiple grouping dimensions when the KPI needs a more detailed business breakdown.","Example: df.groupby(['department','city'])['salary'].mean()","More grouping columns means a finer grain and usually more output rows.","Multiple group keys define a combined grain."],
    ["PY-T044","How do you reset an index after groupby?","Easy","reset_index() converts index levels back into regular columns. This is useful when the grouped result needs further joins or analysis.","Interview answer: I reset the index when I want a flat tabular result for reporting or downstream transformations.","Example: result=df.groupby('department')['salary'].mean().reset_index()","Do not reset the index automatically if the index is intentionally useful for the next operation.","reset_index = turn index labels back into columns."],
    ["PY-T045","How do you read a CSV with Pandas?","Easy","Use pd.read_csv(). For production workflows, specify relevant columns, dtypes, date parsing and missing-value handling where appropriate.","Interview answer: I inspect the file structure and define types carefully rather than relying blindly on inference for important datasets.","Example: df=pd.read_csv('sales.csv', usecols=['date','region','sales'])","For very large files, consider chunksize or a database instead of loading everything at once.","read_csv = common entry point for tabular files."],
    ["PY-T046","How do you export a DataFrame to CSV?","Easy","Use to_csv(). index=False prevents the DataFrame index from being written as an extra column when it is not part of the desired output.","Interview answer: I explicitly decide whether the index is meaningful before exporting.","Example: df.to_csv('clean_sales.csv', index=False)","Do not accidentally export an internal index as a business column.","to_csv = DataFrame to CSV output."],
    ["PY-T047","What is the difference between a Python list and a NumPy array?","Medium","A Python list is a general-purpose container that can hold mixed object types. A NumPy array is designed for numerical computing, usually with a consistent dtype and efficient vectorized operations.","Interview answer: For numerical analysis on large homogeneous data, NumPy arrays are generally more efficient than Python lists.","Example: np.array([1,2,3]) * 2 performs element-wise multiplication.","Do not assume every list operation has the same behavior as an array operation.","List = general container; array = numerical structure."],
    ["PY-T048","What is a dictionary comprehension?","Medium","Dictionary comprehension creates a dictionary from an iterable using a compact expression.","Interview answer: I use it for simple key-value transformations, but keep the expression readable.","Example: squares={x:x*x for x in range(1,6)}","Complex nested comprehensions reduce readability.","Dictionary comprehension = compact dictionary construction."],
    ["PY-T049","What is the difference between shallow copy and deep copy?","Medium","A shallow copy creates a new outer object but nested objects may still be shared. A deep copy recursively copies nested objects.","Interview answer: I use copy.copy for a shallow copy and copy.deepcopy when independent nested structures are required.","Example: import copy; b=copy.deepcopy(a)","Mutating a nested list can reveal the difference between shallow and deep copies.","Shallow = outer copy; deep = nested independent copy."],
    ["PY-T050","What is the difference between a module and a package?","Easy","A module is a Python file containing code. A package is a directory structure used to organize related modules and subpackages.","Interview answer: Modules and packages help split analytics code into reusable, maintainable components.","Example: import pandas is importing a package/library; import my_utils imports a module.","Keep reusable logic outside a giant notebook or script when the project grows.","Module = file, package = organized collection of modules."],
    ["PY-T051","What is PEP 8 and why does it matter?","Easy","PEP 8 is the main style guide for Python code. It covers naming, spacing, indentation and other readability conventions.","Interview answer: Following a consistent style makes team code easier to review, maintain and debug.","Example: use snake_case for normal Python variable and function names.","Style rules improve readability but do not change the underlying algorithm.","PEP 8 = Python style guidance."],
    ["PY-T052","What are *args and **kwargs?","Medium","*args collects extra positional arguments into a tuple. **kwargs collects extra keyword arguments into a dictionary.","Interview answer: They are useful when writing flexible functions, wrappers or reusable utilities.","Example: def log_event(*args, **kwargs): print(args, kwargs)","Do not use them when a clear fixed function signature is better for maintainability.","*args = positional, **kwargs = keyword arguments."],
    ["PY-T053","What is a generator in Python?","Medium","A generator produces values lazily instead of creating the entire collection in memory at once. yield is used to produce values.","Interview answer: Generators are useful for large datasets or streams because they can reduce memory usage.","Example: def numbers():\n    for i in range(1000000):\n        yield i","A generator is consumed as values are requested, so it does not behave like a reusable list automatically.","Generator = lazy sequence."],
    ["PY-T054","What is the difference between for loops and vectorized Pandas operations?","Medium","A for loop processes elements explicitly in Python. Vectorized Pandas or NumPy operations process whole arrays or columns using optimized implementations.","Interview answer: For simple column transformations on large data, I normally prefer vectorized operations. I use loops when the logic is sequential or not naturally vectorized.","Example: df['total']=df['price']*df['qty'] is preferable to iterrows for this calculation.","Do not force vectorization when it makes complex sequential logic incorrect.","Use the simplest correct approach, then profile when performance matters."],
    ["PY-T055","What is method chaining in Pandas?","Medium","Method chaining means applying multiple DataFrame operations in a sequence, often improving readability by showing a transformation pipeline.","Interview answer: Chaining can make cleaning steps easy to follow when each step has a clear purpose.","Example: df.assign(total=df.price*df.qty).query('total > 1000').sort_values('total',ascending=False)","Very long chains can become hard to debug, so split them into named intermediate steps when necessary.","Method chaining = readable transformation pipeline."],
    ["PY-T056","How do you merge data while protecting against unexpected duplicate matches?","Hard","Validate the expected relationship before or during merge. Pandas merge supports validate values such as one_to_one, one_to_many and many_to_one.","Interview answer: I check key uniqueness and row counts before and after a merge because an unexpected many-to-many join can multiply rows and distort KPIs.","Example: orders.merge(customers,on='customer_id',how='left',validate='many_to_one')","Never assume a key is unique just because it has an ID-looking name.","Validate join cardinality to protect analytics results."],
    ["PY-T057","How would you optimize memory usage in a large DataFrame?","Hard","Select only required columns, use appropriate numeric and categorical dtypes, convert repeated strings to category when appropriate, and process large files in chunks.","Interview answer: I inspect memory_usage and data types first, then make changes that preserve the required precision and business meaning.","Example: df['region']=df['region'].astype('category') when the column has a small repeated set of values.","Do not downcast numeric values if it can cause precision or range problems.","Memory optimization = fewer columns + appropriate dtypes + chunking."],
    ["PY-T058","How do you calculate a rolling average?","Medium","rolling(window).mean() calculates a moving average over a defined number of observations.","Interview answer: Rolling metrics are useful for smoothing short-term fluctuations in time-series data.","Example: df['sales_7d_avg']=df['sales'].rolling(7).mean()","Sort by date and define whether the window is based on rows or time before calculating.","Rolling average = local moving summary."],
    ["PY-T059","How do you calculate a rank within each group in Pandas?","Hard","Use groupby with rank, usually after defining the ordering column and rank method. Dense rank does not skip ranks after ties.","Interview answer: I use group-level ranking for use cases such as top employees within each department or top products within each category.","Example: df['rank']=df.groupby('department')['salary'].rank(method='dense',ascending=False)","Choose rank, dense rank or row number behavior according to how ties should be handled.","Groupby + rank = ranking within business groups."],
    ["PY-T060","How would you build a reliable data-cleaning pipeline in Python?","Hard","A reliable pipeline separates loading, validation, cleaning, transformation and output. Each stage should have checks for schema, missingness, duplicates, data types and business rules.","Interview answer: I keep raw data unchanged, make transformations reproducible, validate key metrics after each major step, and log important exceptions.","Example pipeline: read -> validate schema -> standardize types -> clean -> transform -> aggregate -> validate output -> save.","Do not mix manual one-off edits into a repeatable production pipeline without documenting them.","Reliable pipeline = reproducible steps + validation + clear business rules."]
  ];

  const $ = id => document.getElementById(id);
  const esc = s => String(s ?? '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');
  const activeTheory = () => $('pythonTheoryTab') && $('pythonTheoryTab').classList.contains('active');

  function theoryList(){
    const search = (($('search') && $('search').value) || '').toLowerCase().trim();
    const diff = ($('difficulty') && $('difficulty').value) || 'All';
    return THEORY.filter(q => (!search || q[0].toLowerCase().includes(search) || q[1].toLowerCase().includes(search)) && (diff === 'All' || q[2] === diff));
  }

  function showTheory(id){
    const q = THEORY.find(x => x[0] === id);
    if(!q) return;
    document.querySelectorAll('.qbtn').forEach(b => b.classList.toggle('active', b.textContent.startsWith(id+' · ')));
    $('title').textContent = q[0] + ' · ' + q[1];
    $('subtitle').textContent = 'Detailed Python and Pandas explanations in simple interview language.';
    $('page').innerHTML = `
      <div class="card"><span class="badge">Python Theory</span><span class="badge">${esc(q[2])}</span><div class="question">🐍 ${esc(q[1])}</div></div>
      <div class="card"><h3>💡 Simple explanation</h3><div class="answer">${esc(q[3])}</div></div>
      <div class="card"><h3>🎤 Interview answer</h3><div class="detail">${esc(q[4])}</div></div>
      <div class="card"><h3>💻 Example</h3><div class="sample"><pre>${esc(q[5])}</pre></div></div>
      <div class="card"><h3>⚠️ Common mistake</h3><div class="warn">${esc(q[6])}</div></div>
      <div class="card"><h3>🎯 Key takeaway</h3><div class="tip">${esc(q[7])}</div></div>`;
  }

  function renderTheory(){
    if(!activeTheory()) return;
    const arr = theoryList();
    $('stats').textContent = 'Theory: ' + arr.length + ' questions';
    $('nav').innerHTML = '';
    if(!arr.length){
      $('page').innerHTML = '<div class="card"><div class="question">No questions match your filter.</div><p class="meta">Try All difficulty or clear the search box.</p></div>';
      return;
    }
    arr.forEach(q => {
      const b = document.createElement('button');
      b.className = 'qbtn';
      b.textContent = q[0] + ' · ' + q[1];
      b.onclick = () => showTheory(q[0]);
      $('nav').appendChild(b);
    });
    showTheory(arr[0][0]);
  }

  function wire(){
    const theoryTab = $('pythonTheoryTab');
    const practicalTab = $('pythonPracticeTab');
    if(!theoryTab || !practicalTab || !$('nav')) return;

    theoryTab.onclick = () => {
      theoryTab.classList.add('active');
      practicalTab.classList.remove('active');
      if($('search')) $('search').value='';
      if($('difficulty')) $('difficulty').value='All';
      renderTheory();
    };

    if($('search')) $('search').oninput = () => { if(activeTheory()) renderTheory(); };
    if($('difficulty')) $('difficulty').onchange = () => { if(activeTheory()) renderTheory(); };
    renderTheory();
  }

  if(document.readyState === 'loading') document.addEventListener('DOMContentLoaded', wire); else wire();
})();
