(function(){
  const details={
    Q156:{html:`<p>In Pandas, duplicate rows can be removed with <code>drop_duplicates()</code>.</p><pre>df = df.drop_duplicates()</pre><p>You can also choose specific columns that define a duplicate business key:</p><pre>df = df.drop_duplicates(subset=['customer_id'])</pre><p><b>Important:</b> decide which columns define a true duplicate before deleting anything. In real projects, keep the original row count and report how many records were removed.</p>`},
    Q157:{html:`<p>Missing values in Pandas are commonly detected with <code>isna()</code> or <code>isnull()</code>.</p><pre>df.isna().sum()</pre><p>Possible treatments include:</p><ul><li>Keep the value as NULL/NaN when missingness has meaning.</li><li>Fill numeric values with a justified statistic such as median.</li><li>Fill categorical values with a category such as "Unknown".</li><li>Drop rows only when the missing record cannot be used and the business impact is understood.</li></ul><p>The correct choice depends on why the data is missing.</p>`},
    Q158:{html:`<p>A Pandas <code>merge()</code> is similar to a SQL JOIN.</p><pre>result = customers.merge(orders, on='customer_id', how='left')</pre><p><code>how='left'</code> keeps every row from the left DataFrame and adds matching columns from the right. If no match exists, the right-side values become NaN.</p><p>Before merging, check whether the join key is unique. A one-to-many merge can intentionally increase the number of rows.</p>`},
    Q159:{html:`<p>Use <code>groupby()</code> with an aggregation such as <code>mean()</code> to calculate department-level salary statistics.</p><pre>avg_salary = df.groupby('department_id')['salary'].mean()</pre><p>If you want a DataFrame result:</p><pre>avg_salary = df.groupby('department_id', as_index=False)['salary'].mean()</pre><p>The same idea maps directly to SQL: <code>GROUP BY department_id</code> with <code>AVG(salary)</code>.</p>`},
    Q160:{html:`<p>A running total in Pandas can be created with <code>cumsum()</code> after sorting the data in the correct business order.</p><pre>df = df.sort_values('month')
df['running_sales'] = df['sales'].cumsum()</pre><p>If the running total must restart for each department or customer, use <code>groupby(...).cumsum()</code>.</p><p><b>Key point:</b> always sort by the date or sequence column before calculating a running total.</p>`},
    Q161:{html:`<p>A SQL <code>LAG()</code> can be represented in Pandas using <code>shift()</code>.</p><pre>df = df.sort_values(['employee_id','effective_date'])
df['previous_salary'] = df.groupby('employee_id')['salary'].shift(1)</pre><p>The first row of each employee has no previous record, so its lag value is NaN.</p><p>This is useful for salary changes, previous sales, previous orders and week-over-week comparisons.</p>`},
    Q162:{html:`<p>The <b>IQR method</b> identifies unusually high or low numeric values using the interquartile range.</p><p>Calculate Q1, Q3 and <code>IQR = Q3 - Q1</code>. A common rule is:</p><pre>lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR</pre><p>Values outside that range are flagged as potential outliers.</p><p><b>Important:</b> an outlier is not automatically an error. It may represent a genuine business event and should be investigated before removal.</p>`},
    Q163:{html:`<p>Use <code>pd.to_datetime()</code> to convert inconsistent date values into a standard datetime type.</p><pre>df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')</pre><p><code>errors='coerce'</code> converts invalid values to NaT so they can be identified and reviewed.</p><p>Also standardize time zones when timestamps come from different systems. Keep the original source value when auditability is important.</p>`},
    Q164:{html:`<p>To compare two DataFrames and find missing records, choose the business key first, then use a merge with an indicator.</p><pre>check = left.merge(right, on='customer_id', how='outer', indicator=True)
missing = check[check['_merge'] != 'both']</pre><p>This shows records present only in the left or only in the right dataset.</p><p>For a reliable reconciliation, also compare row counts, NULLs, totals and important attributes, not just IDs.</p>`},
    Q165:{html:`<p>A reusable data-cleaning function should accept a DataFrame, perform clearly defined transformations, and return the cleaned DataFrame.</p><pre>def clean_data(df):
    df = df.drop_duplicates()
    df['name'] = df['name'].str.strip()
    df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')
    return df</pre><p>Keep business rules explicit and avoid hiding important assumptions. For production work, add validation checks and logging so the cleaning process is repeatable.</p>`},
    Q166:{html:`<p>A strong project walkthrough follows a simple structure: <b>business problem → data → approach → tools → result/impact</b>.</p><p>Start with what the business needed. Explain the dataset and the main analytical steps. Then mention the tools you used and finish with the measurable outcome.</p><p><b>Example structure:</b> "The business wanted to understand why sales were changing. I combined sales and marketing data, cleaned the dataset, built the analysis in Python and SQL, and created a dashboard that helped stakeholders identify the main drivers."</p>`},
    Q167:{html:`<p>Explain tool choices based on the problem, not because a tool is popular.</p><p>For example, SQL is useful for querying and aggregating structured data, Python for statistical analysis and automation, and Power BI for interactive business reporting.</p><p><b>Interview tip:</b> connect each tool to a specific task and explain why it was practical for the project requirements.</p>`},
    Q168:{html:`<p>When discussing data-cleaning challenges, explain <b>what was wrong, how you detected it, what you changed, and how you validated the result</b>.</p><p>Common examples include duplicate records, NULL values, inconsistent categories, invalid dates, incorrect joins and outliers.</p><p>A strong answer includes validation such as row-count checks, reconciliation totals and sample-level verification.</p>`},
    Q169:{html:`<p>For a tight deadline, explain how you prioritized the work without sacrificing validation.</p><ol><li>Clarify the required business outcome.</li><li>Separate must-have from nice-to-have analysis.</li><li>Use reusable queries or existing datasets where appropriate.</li><li>Validate the critical numbers early.</li><li>Communicate assumptions and limitations.</li></ol><p><b>Interview point:</b> show that you can move quickly while still protecting data quality.</p>`},
    Q170:{html:`<p>Choose a specific lesson from the analysis and connect it to what you changed afterward.</p><p>Examples include learning to validate join grain earlier, documenting KPI definitions, checking data freshness before analysis, or automating repetitive validation.</p><p>A good answer is not simply "I learned SQL." Explain a concrete improvement in your working process.</p>`},
    Q171:{html:`<p>When explaining SQL to a client, focus on the <b>business logic and result</b>, not SQL syntax.</p><p>Instead of saying "I used a window function with LAG," say, "I compared each week's sales with the previous week to identify where sales increased or decreased."</p><p>Use simple examples, numbers and visuals when helpful. Only go deeper into technical implementation if the client asks.</p>`},
    Q172:{html:`<p>Before presenting analysis, validate both the data and the business logic.</p><ol><li>Confirm the KPI definition.</li><li>Check source freshness and completeness.</li><li>Check duplicates and NULLs.</li><li>Validate joins and filters.</li><li>Reconcile totals with a trusted source.</li><li>Manually inspect a sample of records.</li></ol><p>Finally, document the assumptions, formula and reporting period so another person can reproduce the analysis.</p>`}
  };
  function apply(){
    const title=document.getElementById('title');
    const answer=document.querySelector('#page .answer');
    if(!title||!answer)return;
    const m=title.textContent.match(/Q(\d{3})/);
    if(!m)return;
    const item=details['Q'+m[1]];
    if(item) answer.innerHTML=item.html;
  }
  new MutationObserver(apply).observe(document.body,{childList:true,subtree:true});
  setTimeout(apply,100);
})();
